---
development:
  API_HOST: http://0.0.0.0:9292
  SESSION_SECRET: <some secret>

test:
  API_HOST: http://0.0.0.0:9292
  SESSION_SECRET: <some secret>

production:
  API_HOST: http://url.to.api
  SESSION_SECRET: <some secret>
