---
development:
  DB_FILENAME: db/local/dev.db
  OPENAI_API_KEY: "your-api-key"
  GOOGLE_CLOUD_API_TOKEN: "your-api-key"
  SESSION_SECRET: "your session secret key"

test:
  DB_FILENAME: db/local/test.db
  OPENAI_API_KEY: "your-api-key"
  GOOGLE_CLOUD_API_TOKEN: "your-api-key"
  SESSION_SECRET: "your session secret key"

production:
  OPENAI_API_KEY: "your-api-key"
  GOOGLE_CLOUD_API_TOKEN: "your-api-key"
  SESSION_SECRET: "your session secret key"
